apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: us.gcr.io/ticketing-dev-345606/expiration
          env:
            - name: NATS_URL
              value: https://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom: # NATS_CLIENT_ID is set to the pod name
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: redis://expiration-redis-srv
