name: Tests
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekout@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      - run: cd auth && npm install && npm run test:ci
